receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  filelog:
    include_file_path: true
    include:
      - /var/lib/docker/containers/*/*-json.log
    operators:
      - id: parser-docker
        timestamp:
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
          parse_from: attributes.time
        type: json_parser
      - field: attributes.time
        type: remove
      - id: extract_metadata_from_docker_tag
        parse_from: attributes.attrs.tag
        regex: ^(?P<name>[^\|]+)\|(?P<image_name>[^\|]+)\|(?P<id>[^$]+)$
        type: regex_parser
        if: 'attributes?.attrs?.tag != nil'
      - from: attributes.name
        to: resource["service.name"]
        type: move
        if: 'attributes?.name != nil'
      - from: attributes.image_name
        to: resource["service.image.name"]
        type: move
        if: 'attributes?.image_name != nil'
      - from: attributes.id
        to: resource["service.instance.id"]
        type: move
        if: 'attributes?.id != nil'
      - from: attributes.log
        to: body
        type: move
      - id: recombine
        type: recombine
        combine_field: body
        is_first_entry: body matches "^(time=|level=.*? ts=|logger=.*? t=)?\\d{4}-\\d{2}-\\d{2}[T| ]\\d{2}"
      - type: json_parser
        if: body matches "^{.*}$"
        severity:
          parse_from: attributes.Level
          mapping: 
            info: Information
            warn: Warning

  postgresql:
    endpoint: postgres:5432
    transport: tcp
    username: ${env:POSTGRES_OTEL_USER}
    password: ${env:POSTGRES_OTEL_PASSWORD}
    tls:
      insecure: true
    connection_pool:
      max_idle_time: 10m
      max_lifetime: 0
      max_idle: 2
      max_open: 5
    events:
      db.server.query_sample:
        enabled: true
      db.server.top_query:
        enabled: true
    query_sample_collection:
      max_rows_per_query: 100
    top_query_collection:
      max_rows_per_query: 100
      top_n_query: 100
    collection_interval: 30s
    initial_delay: 30s
    metrics:
      postgresql.deadlocks:
        enabled: true
      postgresql.database.locks:
        enabled: true

processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resource/postgresql:
    attributes:
      - key: service.name
        value: "postgres" # The name you want to appear in your backend
        action: upsert
  filter:
    error_mode: ignore
    spans:
      exclude:
        match_type: regexp
        attributes:
          - key: db.statement
            value: ".*otel-collector-ignore.*"
  transform:
    error_mode: ignore
    log_statements:
    - set(log.severity_text, "DEBUG")
    - replace_all_matches(log.attributes, "/user/*/list/*", "/user/{userId}/list/{listId}")
    - replace_all_patterns(log.attributes, "value", "/account/\\d{4}", "/account/{accountId}")
    - set(log.body, log.attributes["db.query.text"])
    - delete_key(log.attributes, "db.query.text")

extensions:
    health_check:
      endpoint: "0.0.0.0:13133"
      check_collector_pipeline: 
        enabled: true 
        interval: "5m" 
        exporter_failure_threshold: 5

exporters:
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/prometheus]
    metrics/postgres:
      receivers: [postgresql]
      processors: [resource/postgresql, memory_limiter, batch, filter]
      exporters: [otlphttp/prometheus]
    logs:
      receivers: [otlp, filelog]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/logs]
    logs/postgres:
      receivers: [postgresql]
      processors: [resource/postgresql, memory_limiter, batch, filter, transform]
      exporters: [otlphttp/logs]

  telemetry:
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
