services:
  otel-collector:
    environment:
      POSTGRES_OTEL_USER: otel
      POSTGRES_OTEL_PASSWORD: otelpassword
    networks:
      - core
  postgres:
    networks:
      - core
  postgres-exporter:
    networks:
      - core
  rabbitmq:
    networks:
      - core
      - available-to-host
  prometheus:
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - core
  grafana:
    networks:
      - available-to-host
  arcane:
    networks:
      - available-to-host
  adminer:
    networks:
      - available-to-host

networks:
  core:
    driver: bridge
    name: core
  
  available-to-host:
    driver: bridge
    attachable: false