{
 "title": "Docker Status Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Container CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container CPU Usage (avg. ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_nanoseconds_total[1m]) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Utilization Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage (User Mode) (avg. ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_usermode_nanoseconds_total[1m])/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Usage (Kernel) (avg. ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_kernelmode_nanoseconds_total[1m]) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Container Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Container Memory Total Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "container_memory_usage_total_bytes / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory File Bytes (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "container_memory_file_bytes / 1000000",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Memory Percent Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "container_memory_percent_ratio", "legendFormat": "{{container_name}}" }
   ]
  }
 ]
}