{
 "title": "Container Network Usage",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Received Network Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_network_io_usage_rx_bytes_total / 1000000",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Transmitted Network Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_network_io_usage_tx_bytes_total /1000000",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Dropped Received Network Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_network_io_usage_rx_dropped_total / 1000000",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Dropped Transmitted Network Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_network_io_usage_tx_dropped_total / 1000000",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}