{
 "title": "System Status Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU load Average (5m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "system_cpu_load_average_5m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System CPU Utilization Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(state) (system_cpu_utilization_ratio)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "System Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "system_processes_count", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "System Memory Usage (Gb)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "system_memory_usage_bytes / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Memory Usage Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "system_memory_utilization_ratio",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(state) (system_network_connections{protocol=\"tcp\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Disk Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "system_disk_pending_operations", "legendFormat": "{{device}}" }
   ]
  }
 ]
}