x-default-logging: &logging
 driver: "json-file"
 options:
   max-size: "100m"
   max-file: "5"
   tag: "{{.Name}}-container|{{.ImageName}}|{{.ID}}"

services:
  # https://github.com/open-telemetry/opentelemetry-demo/blob/main/docker-compose.yml
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    user: 0:0
    volumes:
      # - /:/hostfs:ro
      # https://linuxbeast.com/blog/resolving-wsl-permission-denied-when-connecting-to-docker-daemon/#:~:text=If%20you%20are%20using%20Windows,access%20the%20Docker%20daemon%20socket.
      # https://stackoverflow.com/questions/48957195/how-to-fix-docker-permission-denied
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers:ro
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    depends_on:
      jaeger:
        condition: service_healthy
      loki:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - telemetry-internal
    logging: *logging

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    restart: unless-stopped
    command: ["--config", "/jaeger/config.yaml"]
    volumes:
      - ./jaeger/jaeger-config.yaml:/jaeger/config.yaml
      - jaeger-data:/tmp
    ports:
      - "16686:16686" # Web UI
      - "4317"
    healthcheck:
      test: wget -q -t 1 -O - http://localhost:13132/status | grep -q "\"healthy\":true" || exit 1
      interval: 5s
      timeout: 1s
      retries: 12  # try for 1 minute
    environment:
      - METRICS_STORAGE_TYPE=prometheus
    networks:
      - telemetry-internal
    deploy:
      resources:
        limits:
          memory: 512m
    logging: *logging

  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --web.enable-otlp-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    healthcheck:
      test: wget -q -t 1 -O - http://localhost:9090/-/healthy | grep -q "Prometheus Server is Healthy."
      interval: 5s
      timeout: 1s
      retries: 12  # try for 1 minute
    depends_on:
      jaeger:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - telemetry-internal
    deploy:
      resources:
        limits:
          memory: 512m
    logging: *logging

  loki:
    image: grafana/loki:3.5.9 # Loki 3.6.x currently has broken it's healthcheck, 2025-12-24
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-storage:/loki
    networks:
      - telemetry-internal
    healthcheck:
      test: wget  -q -t 1 -O - http://localhost:3100/ready | grep -q -w ready || exit 1
      interval: 5s
      timeout: 1s
      retries: 12  # try for 1 minute
    logging: *logging

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    restart: always
    volumes:
      - /:/host:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/host'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|var|run|snap)($$|/)'
    pid: host
    networks:
      - telemetry-internal
    deploy:
      resources:
        limits:
          memory: 512m
    logging:
      driver: local
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    restart: always
    networks:
      - telemetry-internal
    deploy:
      resources:
        limits:
          memory: 512m
    logging:
      driver: local

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_healthy
      jaeger:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - telemetry-internal
    healthcheck:
      test: curl -f http://otel-collector:13133 && curl -f http://localhost:3000/api/health || exit 1  # Test for otel-collector health here since the otel-collector image can not do it itself
      interval: 5s
      timeout: 1s
      retries: 12  # try for 2 minutes
    deploy:
      resources:
        limits:
          memory: 512m
    logging: *logging

  

volumes:
  grafana-storage: {}
  loki-storage: {}
  prometheus-data: {}
  jaeger-data: {}

networks:
  telemetry-internal:
    driver: bridge
    internal: true
